-- Ensure API roles can access objects in the public schema.
-- This is required in addition to RLS/table policies.
DO $$
BEGIN
	IF to_regrole('authenticated') IS NOT NULL THEN
		EXECUTE 'GRANT USAGE ON SCHEMA public TO authenticated';
		EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated';
		EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated';
		EXECUTE 'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO authenticated';
	END IF;

	IF to_regrole('anon') IS NOT NULL THEN
		EXECUTE 'GRANT USAGE ON SCHEMA public TO anon';
		EXECUTE 'GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon';
		EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon';
		EXECUTE 'GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon';
	END IF;

	-- Keep future objects accessible to API roles unless overridden later.
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO authenticated';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO authenticated';

	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO anon';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO anon';
END
$$;